VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "TemplatePredeclaredClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
'Rubberduck annotations
'@Folder("Templates")
'@ModuleDescription "Template for classes"
'@PredeclaredId

'Copyright(c) 2023 Mark Johnstone
'MarkJohnstoneGitHub/VBA-dotnet-CorLib is licensed under the MIT License
'@Version v1.0 February 11, 2023
'@LastModified February 11, 2023

'@DotNetReferences

'------------------------------------------------------------------
'Compiler Constants
'------------------------------------------------------------------
'@CompilerConstants

'------------------------------------------------------------------
'Constants
'------------------------------------------------------------------

'------------------------------------------------------------------
'Types
'------------------------------------------------------------------
'Private Type TTemplate

'End Type

'------------------------------------------------------------------
'Private Variables
'------------------------------------------------------------------
'Private this as TTemplate

'------------------------------------------------------------------
'Constructors and destructors
'------------------------------------------------------------------
'Private Sub Class_Initialize()
'End Sub
'
'Private Sub Class_Terminate()
'End Sub

'------------------------------------------------------------------
'Class Constructors
'------------------------------------------------------------------

'------------------------------------------------------------------
'Properties
'------------------------------------------------------------------

'------------------------------------------------------------------
'Public Methods
'------------------------------------------------------------------

'------------------------------------------------------------------
'Private Methods
'------------------------------------------------------------------

'------------------------------------------------------------------
'Interfaces
'------------------------------------------------------------------
